In [1]:
#1
a = int(input("Nhap gia tri a: "))
b = int(input("Nhap gia tri b: "))

Tong = a + b
Hieu = a - b
Tich = a * b
Thuong = a / b

print(f"Tong la: {Tong}")
print(f"Hieu la: {Hieu}")
print(f"Tich la: {Tich}")
print(f"Thuong la: {Thuong}")

Nhap gia tri a: 5
Nhap gia tri b: 4
Tong la: 9
Hieu la: 1
Tich la: 20
Thuong la: 1.25


In [2]:
#2
a = 'Hello World'
c = a[2:5]
print(c)

llo


In [3]:
#3
a = '  Hello World  '
s = a.strip()
h = a.strip().upper()
j = a.strip().replace("H","J")
print(f"Goc: {a}")
print(f"Xoa khoang trang: {s}")
print(f"Viet hoa: {h}")
print(f"Thay the: {j}")

Goc:   Hello World  
Xoa khoang trang: Hello World
Viet hoa: HELLO WORLD
Thay the: Jello World


In [4]:
#4
a = int(input("Nhap gia tri a: "))
b = int(input("Nhap gia tri b: "))

if a > b:
  print('Hello World!')

Nhap gia tri a: 2
Nhap gia tri b: 4


In [5]:
#5
a = int(input("Nhap gia tri a: "))
b = int(input("Nhap gia tri b: "))

if a == b:
  print('Yes')
else:
  print('No')

Nhap gia tri a: 2
Nhap gia tri b: 4
No


In [6]:
#6
a = int(input("Nhap gia tri a: "))
b = int(input("Nhap gia tri b: "))

if a == b:
  print('1')
elif a > b:
  print('2')
else:
  print('3')

Nhap gia tri a: 1
Nhap gia tri b: 3
3


In [19]:
22
#7
a = int(input("Nhap gia tri a: "))
b = int(input("Nhap gia tri b: "))
d = int(input("Nhap gia tri d: "))
if a == b and b == d:
  print('Hello World')

Nhap gia tri a: 2
Nhap gia tri b: 2
Nhap gia tri d: 2
Hello World


In [16]:
#8
a = int(input("Nhap gia tri a: "))
b = int(input("Nhap gia tri b: "))
c = int(input("Nhap gia tri c: "))
d = int(input("Nhap gia tri d: "))
if a == b or c == d:
  print('Hello World')

Nhap gia tri a: 2
Nhap gia tri b: 2
Nhap gia tri c: 4
Nhap gia tri d: 5
Hello World


In [10]:
#9
a = int(input("Nhap gia tri a: "))
b = int(input("Nhap gia tri b: "))
print('Yes') if a > b else print('No')

Nhap gia tri a: 5
Nhap gia tri b: 4
Yes


In [21]:
2#cau 10
a=int(input("Nhap a:"))
b=int(input("Nhap b:"))
def myfunc(a,b):
  print("A") if a > b else print("=") if a == b else print("B")
myfunc(a,b)

Nhap a:3
Nhap b:2
A


In [11]:
#cau 11
import numpy as np
# Tạo một mảng 2x3 với các số nguyên ngẫu nhiên từ 0 đến 10
data = np.random.randint(0, 10, size=(2, 3))
def myfunc(data):
  print(data)
  ptuchan = data[data % 2 == 0]
  print("Phần tử chẵn:",ptuchan)
myfunc(data)

[[9 6 9]
 [9 4 9]]
Phần tử chẵn: [6 4]


In [12]:
#Cau 12
import numpy as np
data = np.arange(0, 1000) # Tạo một mảng từ 0 đến 999 (không bao gồm 1000)
print(data)
a=data[(data % 3 == 0) | (data % 5 == 0)]
print("*********************************")
print(a)
print("*********************************")
print("tong cac so tu 0 den 999 la boi cua 3 va 5 la:",np.sum(a))

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

In [13]:
#cau 13
import numpy as np

mang1 = np.array([1, 2, 3])
mang2 = np.array([10, 20, 30, 40, 50])


max_len = max(len(mang1), len(mang2))


mang1_padded = np.pad(mang1, (0, max_len - len(mang1)), 'constant')
mang2_padded = np.pad(mang2, (0, max_len - len(mang2)), 'constant')


ket_qua = mang1_padded + mang2_padded

print("Mảng 1:", mang1)
print("Mảng 2:", mang2)
print("Kết quả cộng (giữ lại phần dư):", ket_qua)

Mảng 1: [1 2 3]
Mảng 2: [10 20 30 40 50]
Kết quả cộng (giữ lại phần dư): [11 22 33 40 50]


In [14]:
#cau 14
import numpy as np
#Nhập số dòng và cột của ma trận:
n=int(input("n="))
m=int(input("m="))
def myfunc(n,m):
  data = np.random.randint(0, 100, size=(n, m))
  print(data)
  print("**************")
  k=int(input("Nhập k:"))
  print("dòng k",data[k])
  print("cột k",data[:,k:k+1])
  max=np.sum(data[0])
  for i in range(n):
     row=data[i]
     if(np.sum(row)>max):
      max=np.sum(row)
  print("dòng có tổng lớn nhất:",max)
  min=np.prod(data[:,:1])
  for i in range(m):
    column=data[:,:i+1]
    if(np.prod(column)<min):
      min=np.prod(column)
  print("Cột có tích nhỏ nhất:",min)
  # In ra các phần tử thuộc dòng chẵn và cột lẻ
  print("Các phần tử ở dòng chẵn và cột lẻ:")
  found_elements = []
  for i in range(n): # Duyệt qua chỉ số dòng
    if i % 2 == 0: # Kiểm tra dòng chẵn (chỉ số 0, 2, 4,...)
      for j in range(m): # Duyệt qua chỉ số cột
        if j % 2 != 0: # Kiểm tra cột lẻ (chỉ số 1, 3, 5,...)
          found_elements.append(data[i, j])
          print(f"({i}, {j}): {data[i, j]}")
  if not found_elements:
      print("Không tìm thấy phần tử nào thỏa mãn điều kiện.")
  print(f"Giá trị trung bình các phần tử thuộc biên: {(np.sum(data[:,:1])+np.sum(data[:,m-1:]))/(2*m)}")
  size_data=np.size(data)
 # print(data[:,1:m-1])
  print(f"Giá trị trung bình tích các phần tử khôngthuộc biên: {np.prod(data[:,1:m-1])**(1/(size_data-n*2))}")
myfunc(n,m)

n=5
m=6
[[50 44 83 32 48 37]
 [34 76 27 20 17 46]
 [32 77 86 74 95 76]
 [87  4 76 13 64 31]
 [57 34 80 97 28  5]]
**************
Nhập k:2
dòng k [32 77 86 74 95 76]
cột k [[83]
 [27]
 [86]
 [76]
 [80]]
dòng có tổng lớn nhất: 440
Cột có tích nhỏ nhất: -8586876951631757312
Các phần tử ở dòng chẵn và cột lẻ:
(0, 1): 44
(0, 3): 32
(0, 5): 37
(2, 1): 77
(2, 3): 74
(2, 5): 76
(4, 1): 34
(4, 3): 97
(4, 5): 5
Giá trị trung bình các phần tử thuộc biên: 37.916666666666664
Giá trị trung bình tích các phần tử khôngthuộc biên: 8.858305685229892


In [15]:
#Câu 15:
import datetime

# a. Xây dựng cấu trúc SINHVIEN mô tả một sinh viên
class SINHVIEN:
    def __init__(self, ma_sinh_vien, ten, nam_sinh, diem_trung_binh):
        # Validate ma_sinh_vien (10 ký tự)
        if not isinstance(ma_sinh_vien, str) or len(ma_sinh_vien) != 10:
            raise ValueError("Mã sinh viên phải là chuỗi có 10 ký tự.")
        self.ma_sinh_vien = ma_sinh_vien

        # Validate ten (tối đa 20 ký tự)
        if not isinstance(ten, str) or len(ten) > 20:
            raise ValueError("Tên phải là chuỗi tối đa 20 ký tự.")
        self.ten = ten

        # Validate nam_sinh (số nguyên)
        if not isinstance(nam_sinh, int) or not (1900 <= nam_sinh <= datetime.datetime.now().year):
            raise ValueError("Năm sinh phải là số nguyên hợp lệ.")
        self.nam_sinh = nam_sinh

        # Validate diem_trung_binh (số thực)
        if not isinstance(diem_trung_binh, (int, float)) or not (0 <= diem_trung_binh <= 10):
            raise ValueError("Điểm trung bình phải là số thực từ 0 đến 10.")
        self.diem_trung_binh = diem_trung_binh

    def __str__(self):
        return f"Mã SV: {self.ma_sinh_vien}, Tên: {self.ten}, Năm sinh: {self.nam_sinh}, ĐTB: {self.diem_trung_binh}"

# b. Cho một mảng có n sinh viên.
# Ví dụ tạo một mảng (list) các sinh viên
students = [
    SINHVIEN("01TH000001", "Nguyen Van A", 2003, 7.5),
    SINHVIEN("02DH000002", "Tran Thi B", 2004, 4.8),
    SINHVIEN("03TH000003", "Le Van C", 2002, 9.0),
    SINHVIEN("04DH000004", "Pham Thi Lan", 2005, 6.2),
    SINHVIEN("05TH000005", "Hoang Van D", 2001, 3.5),
    SINHVIEN("06DH000006", "Phan Thi E", 2004, 5.0),
    SINHVIEN("07KT000007", "Nguyen Thi Lan", 2003, 8.1)
]

print("Danh sách sinh viên:")
for s in students:
    print(s)

# c. Viết hàm cho biết có bao sinh viên đủ điều kiện lên lớp
def count_eligible_students(student_list):
    count = 0
    for student in student_list:
        if student.diem_trung_binh >= 5.0:
            count += 1
    return count

eligible_count = count_eligible_students(students)
print(f"\nSố sinh viên đủ điều kiện lên lớp: {eligible_count}")

import datetime

# d. Xuất các sinh viên đủ 20 tuổi
def print_20_year_old_students(student_list):
    current_year = datetime.datetime.now().year
    print("\nCác sinh viên đủ 20 tuổi:")
    found = False
    for student in student_list:
        if (current_year - student.nam_sinh) == 20:
            print(student)
            found = True
    if not found:
        print("Không có sinh viên nào đủ 20 tuổi.")

print_20_year_old_students(students)

# e. Đếm số sinh viên học hệ đại học
def count_university_students(student_list):
    count = 0
    for student in student_list:
        # Mã sinh viên chứa 2 ký tự DH ở vị trí 2,3 (index 1, 2)
        if student.ma_sinh_vien[1:3] == "DH":
            count += 1
    return count

university_students_count = count_university_students(students)
print(f"\nSố sinh viên học hệ đại học: {university_students_count}")

# f. Cho biết trong mảng có bao nhiêu sinh viên có tên «Lan»
def count_students_by_first_name(student_list, first_name):
    count = 0
    for student in student_list:
        # Tách tên cuối cùng
        student_first_name = student.ten.split()[-1]
        if student_first_name == first_name:
            count += 1
    return count

lan_count = count_students_by_first_name(students, "Lan")
print(f"\nSố sinh viên có tên 'Lan': {lan_count}")

# g. Cho biết trong mảng có bao nhiêu sinh viên có họ «Phan»
def count_students_by_last_name(student_list, last_name):
    count = 0
    for student in student_list:
        # Tách họ
        student_last_name = student.ten.split()[0]
        if student_last_name == last_name:
            count += 1
    return count

phan_count = count_students_by_last_name(students, "Phan")
print(f"\nSố sinh viên có họ 'Phan': {phan_count}")

Danh sách sinh viên:
Mã SV: 01TH000001, Tên: Nguyen Van A, Năm sinh: 2003, ĐTB: 7.5
Mã SV: 02DH000002, Tên: Tran Thi B, Năm sinh: 2004, ĐTB: 4.8
Mã SV: 03TH000003, Tên: Le Van C, Năm sinh: 2002, ĐTB: 9.0
Mã SV: 04DH000004, Tên: Pham Thi Lan, Năm sinh: 2005, ĐTB: 6.2
Mã SV: 05TH000005, Tên: Hoang Van D, Năm sinh: 2001, ĐTB: 3.5
Mã SV: 06DH000006, Tên: Phan Thi E, Năm sinh: 2004, ĐTB: 5.0
Mã SV: 07KT000007, Tên: Nguyen Thi Lan, Năm sinh: 2003, ĐTB: 8.1

Số sinh viên đủ điều kiện lên lớp: 5

Các sinh viên đủ 20 tuổi:
Không có sinh viên nào đủ 20 tuổi.

Số sinh viên học hệ đại học: 0

Số sinh viên có tên 'Lan': 2

Số sinh viên có họ 'Phan': 1
